stages:
  - test
  - build
  - deploy

doxec:
  image: python:3
  stage: test
  script:
    - pip install doxec numpy
    - doxec *.md

build_image:
  stage: build
  variables:
    DOCKER_FILE: Dockerfile
    TAG: latest
    IMAGE_NAME: base-python
    CI_REGISTRY: gitlab-registry.cern.ch
    TO: '${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${IMAGE_NAME}:${TAG}'
  script:
    # The script gets overwritten in jobs tagged docker-image-build
    - ignore
  except:
    - tags
  tags:
    - docker-image-build

push_to_hub:
  stage: deploy
  except:
    - tags
  image: matthewfeickert/skopeo-docker:latest
  variables:
    TAG: latest
    IMAGE_NAME: base-python
  script:
    - /home/docker/skopeo copy
      --src-creds ${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds ${DH_USERNAME}:${DH_PASSWORD}
      docker://${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${TAG}
      docker://${DH_USERNAME}/${IMAGE_NAME}:${TAG}


