doxec:
  image: python:3
  script:
    - pip install doxec numpy
    - doxec *.md

build_image:
  variables:
    DOCKER_FILE: Dockerfile
    TAG: latest
    IMAGE_NAME: base-python
    CI_REGISTRY: gitlab-registry.cern.ch
    TO: '${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${IMAGE_NAME}:${TAG}'
  script:
    # The script gets overwritten in jobs tagged docker-image-build
    - ignore
  except:
  - tags
  tags:
    - docker-image-build
